### ISSUE TITLE
Overwriting classes instead of merging.

### ISSUE THREAD

**Issue by Aaron-Pool** [ParkerD559/vue-emotion-plugin#9]
Hey!

Finally got around to playing around with this library, but some issues came up when I tried it as a drop in replacement for legacy `vue-emotion`, the biggest of which is that you're not taking into account existing classes that might exist on a VNode.

Checkout this line from `wrapper.js`:

```js
    // Add the target class if need be
    const classes = this.$_targetClass
        ? [emotionClass, this.$_targetClass]
        : [emotionClass]

    return createElement(
        this.$_styledFrom,  // Base component even if styled multiple times
        { ...context.data, class: classes },
        context.children
    );
```

See? You're taking into account a `targetClass` for selector targeting, but when the root node of the component being styled already has a `class` attribute, it's getting wiped out.

**Comment by Aaron-Pool** [comment]
Oh, and I fixed it locally, if you're interested in a PR. But if you want to handle it yourself, I get that too 👌

**Comment by dparker2** [comment]
@Aaron-Pool Hey sorry I've been super busy and just finally noticed this. Thanks for addressing that!

**Comment by dparker2** [comment]
should be in `v0.0.5` now! thanks!
